config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy'
  resources :users
  resources :messages, only: [:new, :create]
  resources :stocks
  post '/setAsset' => 'assets#setAsset'
  post '/setPayload' => 'assets#setPayload'

end

app/views/partials/_flash_messages.js.erb
<% flash.each do |type, message| %>
  Materialize.toast("<%= message.html_safe %>", 4000);// 4000 is the duration of the toast
<% end %>

app/views/partials/_nav.html.erb
<nav>
	<div class="nav-wrapper">
		<%= link_to :root, class: "brand-logo center", id: "brand-logo" do %>
			<i class="medium material-icons left">textsms</i>Stock Message Service
		<% end %>
		<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
		<ul id="nav-mobile" class="left hide-on-med-and-down">
			<% if !current_user %>
				<li>
					<%= link_to new_user_path, class: "" do %>
						<i class="medium material-icons left">perm_contact_calendar</i>Sign Up for SMS Updates
					<% end %>
				</li>
				<li>
					<%= link_to login_path, class: "" do %>
						<i class="medium material-icons left">lock_open</i>Login
					<% end %>
				</li>
			<% else %>
				<li>
					<%= link_to user_path(current_user.id), class: "" do %>
						<i class="medium material-icons left">perm_identity</i>Portfolio 
					<% end %>
				</li>
				<li>
					<%= link_to logout_path, class: "", method: :delete do %>
						<i class="medium material-icons left">lock_outline</i>Logout

					<% end %>
				</li>
			<% end %>
		</ul>
		<ul id="mobile-demo" class="side-nav collection left">
			<% if !current_user %>
				<li class="collection-item">
					<%= link_to new_user_path, class: "" do %>
						<i class="medium material-icons left">perm_contact_calendar</i>Sign Up for SMS Updates
					<% end %>
				</li>
				<li class="collection-item">
					<%= link_to login_path, class: "" do %>
						<i class="medium material-icons left">lock_open</i>Login
					<% end %>
				</li>
			<% else %>
				<li class="collection-item">
					<%= link_to user_path(current_user.id), class: "" do %>
						<i class="medium material-icons left">perm_identity</i>Portfolio 
					<% end %>
				</li>
				<li class="collection-item">
					<%= link_to logout_path, class: "", method: :delete do %>
						<i class="medium material-icons left">lock_outline</i>Logout

					<% end %>
				</li>
			<% end %>
		</ul>
	</div>
</nav>

app/views/partials/_stock_info.html.erb
<p class="center">Updated At: <%= @stock.updated_at.in_time_zone("Eastern Time (US & Canada)").strftime '%r' %></p>

	<%= form_tag "/setPayload", method: "post", remote: true do %>
		<%= hidden_field_tag "id", @asset.id %>

		<ul class="collection row">
			<li class="collection-item col s12">
				
				<strong>Average Total Volume:</strong><br /><%= @stock.avg_total_volume %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"avg_total_volume",
								@payload["avg_total_volume"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>Calculation Price:</strong><br /> <%= @stock.calculation_price %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"calculation_price",
								@payload["calculation_price"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>Change:</strong><br /> <%= @stock.change %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"change",
								@payload["change"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>Percent Change:</strong><br /> <%= @stock.change_percent%>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"change_percent",
								@payload["change_percent"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>Close:</strong><br /><%= @stock.close %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"close",
								@payload["close"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>Closing Time:</strong><br /> <%= @stock.close_time %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"close_time",
								@payload["close_time"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>Delayed Price:</strong><br /> <%= @stock.delayed_price %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"delayed_price",
								@payload["delayed_price"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>Time of Delayed Price:</strong><br /> <%= @stock.delayed_price_time %>
				
				<div class="switch secondary-content">
					<label>
						Off
						<%= check_box_tag "payload[]",
								"delayed_price_time",
								@payload["delayed_price_time"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>High:</strong><br /> <%= @stock.high %>
				
				<div class="switch secondary-content">
					<label>
  				Off
					<%= check_box_tag "payload[]",
							"high",
							@payload["high"] ? true : false %>
					<span class="lever"></span>
					On
					</label>
				</div>
			</li>
			<!-- Add highlighting for minus -->
			<li class="collection-item col s12">
				
				<strong>Latest Price:</strong><br /> <%= @stock.latest_price %>
				
				<div class="switch secondary-content">
					<label>
  				Off
					<%= check_box_tag "payload[]",
							"latest_price",
							@payload["latest_price"] ? true : false %>
					<span class="lever"></span>
					On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>Latest Source: </strong><br /><%= @stock.latest_source %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"latest_source",
								@payload["latest_source"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>Latest Time:</strong><br /> <%= @stock.latest_time %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"latest_time",
								@payload["latest_time"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>Latest Update:</strong><br /><%= @stock.latest_update %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"latest_update",
								@payload["latest_update"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>Latest Volume:</strong><br /> <%= @stock.latest_volume %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"latest_volume",
								@payload["latest_volume"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>Low:</strong><br /> <%= @stock.low %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"low",
								@payload["low"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>Market Cap:</strong><br /> <%= @stock.market_cap %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"market_cap",
								@payload["market_cap"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>Open:</strong><br /> <%= @stock.open %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"open",
								@payload["open"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			
			<li class="collection-item col s12">
				
				<strong>Open Time:</strong><br /> <%= @stock.open_time %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"open_time",
								@payload["open_time"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>PE Ratio:</strong><br /> <%= @stock.pe_ratio %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"pe_ratio",
								@payload["pe_ratio"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>Previous Close:</strong><br /> <%= @stock.previous_close %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"previous_close",
								@payload["previous_close"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>Primary Exchange:</strong><br /> <%= @stock.primary_exchange %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"primary_exchange",
								@payload["primary_exchange"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>Sector:</strong><br /> <%= @stock.sector %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"sector",
								@payload["sector"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>52 Week High:</strong><br /> <%= @stock.week52_high %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"week52_high",
								@payload["week52_high"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>52 Week Low:</strong><br /> <%= @stock.week52_low %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"week52_low",
								@payload["week52_low"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
			<li class="collection-item col s12">
				
				<strong>Year to Date Change:</strong><br /> <%= @stock.ytd_change %>
				
				<div class="switch secondary-content">
					<label>
    				Off
						<%= check_box_tag "payload[]",
								"ytd_change",
								@payload["ytd_change"] ? true : false %>
						<span class="lever"></span>
						On
					</label>
				</div>
			</li>
		</ul>
		<%= submit_tag 'Save', id: "payloadBTN", class: 'btn btn-large btn-primary' %>
	<% end %>
</div>
	

app/views/partials/_stock_modal.html.erb
<!-- Modal -->
<div class="modal bottom-sheet" id="myModal">
	<div class="modal-content">
		<%= form_tag "/setAsset", method: "POST", remote: true do %>
			<div class="modal-header center">
				<h4>Set Price Alerts</h4>
				<p class="center">If the finish time is before the start time the program will assume that the finish time is for the next day.</p>
				<p class="center">Start and finish times must be filled out, but either a ceiling or roof must be entered.</p>
			</div>
			<div class="modal-body center">
				<%= hidden_field_tag :asset_id, @asset.id %>
				<div class="input-field inline">
					<%= label_tag :high, "Set Ceiling:" %>
					<%= number_field_tag :high, @asset.high, step: 0.01 %>
				</div>
				<div class="input-field inline">
					<%= label_tag :low, "Set Floor:" %>
					<%= number_field_tag :low, @asset.low, step: 0.01 %>
				</div>
				<div class="row">
                    <div class="input-field inline">
                        <label for="start_time">Start Time</label>
                        <input id="startTime" class="timepicker" name="start_time" type="time" class="active">
                        <% unless @asset.start_time.nil? %>
                        	<%= hidden_field_tag :start_time, @asset.start_time.in_time_zone('Eastern Time (US & Canada)').strftime("%H:%M") %>
                        <% else %>
							<%= hidden_field_tag :start_time, Time.now.strftime("%H:%M") %>
                        <% end %>
                    </div>
                   
                     <div class="input-field inline">
                        <label for="finish_time">Finish Time</label>
                        <input id="finishTime" class="timepicker" name="finish_time" type="time" class="active">
                         <% unless @asset.finish_time.nil? %>
                        	<%= hidden_field_tag :finish_time, @asset.finish_time.in_time_zone('Eastern Time (US & Canada)').strftime("%H:%M") %>
                        <% else %>
							<%= hidden_field_tag :finish_time, Time.now.in_time_zone('Eastern Time (US & Canada)').strftime("%H:%M") %>
                        <% end %>
                    </div>
                </div>
			</div>
			<div id="modal-footer" class="modal-footer">
				<button type="button" class="btn btn-default" onClick="$('.modal').modal('close');">Close</button>
				<%= button_tag id: "saveBTN", class: "btn", disable_with: "Saving..." do %>
					 <i class="material-icons left">input</i>Save
				<% end %>
			</div>
		<% end %>
	</div>
</div>